name: Run Tests on Push or Pull Request to Main

on:
  push:
    branches:
      - main  # Run tests on any push to the main branch
  pull_request:
    branches:
      - main  # Run tests on any pull request to the main branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Set your desired Python version

      - name: Install dependencies from requirements.txt
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            echo "requirements.txt not found, proceeding with only pytest dependencies"
          fi
          pip install pytest pytest-cov  # Ensure pytest and pytest-cov are installed
          pip list  # List installed packages for debugging

      - name: Run tests with pytest and enforce 70% coverage
        run: |
          pytest --cov=app --cov-fail-under=70
